title: Architecturecoding
tagline: Personal Blog Page
author:
  name: Kevser Sirca
  url: https://twitter.com/kev_src

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Build Settings

paginate: 2

tags_path: /tags/
categories_path: /categories/
